//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class AspNetUsers
{
    public string Id { get; set; }
    public string Email { get; set; }
    public bool EmailConfirmed { get; set; }
    public string PasswordHash { get; set; }
    public string SecurityStamp { get; set; }
    public string PhoneNumber { get; set; }
    public bool PhoneNumberConfirmed { get; set; }
    public bool TwoFactorEnabled { get; set; }
    public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
    public bool LockoutEnabled { get; set; }
    public int AccessFailedCount { get; set; }
    public string UserName { get; set; }
}

public partial class Predbiljezba
{
    public int Id { get; set; }
    public System.DateTime Datum { get; set; }
    public string Ime { get; set; }
    public string Prezime { get; set; }
    public string Adresa { get; set; }
    public string Email { get; set; }
    public int IdSeminar { get; set; }
    public string Status { get; set; }
    public string Kontakt { get; set; }

    public virtual Seminar Seminar { get; set; }
}

public partial class Seminar
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Seminar()
    {
        this.Predbiljezba = new HashSet<Predbiljezba>();
    }

    public int Id { get; set; }
    public string Naziv { get; set; }
    public string Opis { get; set; }
    public System.DateTime DatumPocetka { get; set; }
    public string Predavac { get; set; }
    public int BrojSati { get; set; }
    public Nullable<decimal> Cijena { get; set; }
    public Nullable<int> BrojPredbiljezbi { get; set; }
    public bool Zatvoren { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Predbiljezba> Predbiljezba { get; set; }
}
